const { safeClone } = require('./safe-json');

class ExecutionManager {
  constructor(database) {
    this.database = database;
    this.executionMap = new Map();
  }

  // Begins tracking a new execution, given an already-generated executionId -
  // generated by the caller (the global inject/http-in hook), which must
  // stamp the id onto the message synchronously (so every destination wire
  // of that send() carries the same id) before awaiting this method's
  // actual database write.
  //
  // Records the ONE 'input' message for this execution - the origin node's
  // outgoing payload, i.e. what starts everything. Every node after this
  // one only ever gets an 'output' entry (see recordNodeExit), which skips
  // originNodeId entirely so the origin doesn't end up with a second,
  // redundant entry once its own onComplete later fires.
  async beginExecution(executionId, flowId, flowName, initialMessage, originNodeId) {
    await this.database.createExecution({
      executionId,
      flowId,
      flowName,
      originNodeId,
      initialMessage: safeClone(initialMessage)
    });

    this.executionMap.set(executionId, {
      status: 'RUNNING',
      startTime: Date.now(),
      originNodeId,
      autoReplayAttempt: 0
    });

    await this.database.recordMessage(executionId, originNodeId, initialMessage, 'input', {
      nodeName: flowName,
      isFirst: true
    });
  }

  // Records that a node finished processing (called from the global
  // onComplete hook - see execution-resilience.js - so this fires for every
  // node in a tracked flow automatically). Skipped for the origin node
  // itself - its one entry was already recorded as 'input' by
  // beginExecution.
  // options.isResult flags the message that represents the execution's
  // actual outcome (an http response node's completion, or the dedicated
  // execution-complete marker node's). options.isError flags a completion
  // that carried an error (see recordFailure in execution-resilience.js).
  async recordNodeExit(executionId, nodeId, nodeName, message, options = {}) {
    const execution = this.executionMap.get(executionId);
    if (execution && nodeId === execution.originNodeId) {
      return executionId;
    }

    await this.database.recordMessage(executionId, nodeId, message, 'output', {
      nodeName,
      isResult: options.isResult === true,
      isError: options.isError === true,
      isReplayPoint: options.isReplayPoint === true,
      isAutoReplayPoint: options.isAutoReplayPoint === true
    });
    return executionId;
  }

  // Synchronous, in-memory read of how many times the current lineage has
  // already been auto-retried - used by execution-resilience.js's
  // recordFailure to compute the NEXT attempt number without an extra DB
  // round-trip (the entry is gone by the time failExecution below deletes
  // it, so callers must read this BEFORE calling failExecution).
  getAutoReplayAttempt(executionId) {
    const execution = this.executionMap.get(executionId);
    return execution ? (execution.autoReplayAttempt || 0) : 0;
  }

  async completeExecution(executionId, completionNodeId) {
    const execution = this.executionMap.get(executionId);
    if (execution) {
      execution.status = 'COMPLETED';
      execution.endTime = Date.now();
      execution.completionNode = completionNodeId;
    }

    const duration = execution ? execution.endTime - execution.startTime : 0;

    await this.database.updateExecution(executionId, {
      status: 'COMPLETED',
      completionNodeId,
      duration
    });

    this.executionMap.delete(executionId);
  }

  async failExecution(executionId, nodeId, error) {
    const execution = this.executionMap.get(executionId);
    if (execution) {
      execution.status = 'FAILED';
      execution.endTime = Date.now();
    }

    const duration = execution ? execution.endTime - execution.startTime : 0;

    await this.database.recordError(executionId, nodeId, error);
    await this.database.updateExecution(executionId, {
      status: 'FAILED',
      failureNodeId: nodeId,
      duration
    });

    this.executionMap.delete(executionId);
  }

  async getExecution(executionId) {
    return await this.database.getExecution(executionId);
  }

  // Every message recorded at a 'replay-point' node for this execution -
  // see the `isReplayPoint` flag set in execution-resilience.js's
  // recordOneCompletion. Used to offer "resume from checkpoint" as an
  // ADDITIONAL replay option alongside the always-available full restart
  // (see beginRestart) - not a gate on whether replay is possible at all.
  async getReplayPoints(executionId) {
    return await this.database.getReplayPoints(executionId);
  }

  // Walks an execution's replayOf chain back to the execution that has none -
  // i.e. the one a real inject/http-in origin actually began - so a flow is
  // always fully repeatable from the very beginning, no matter how many
  // times it's already been resumed from some later checkpoint since. Caps
  // via `seen` purely as a defensive guard against a corrupted/circular
  // chain; a real chain is always a straight line back to one root.
  async getRootExecution(executionId) {
    let execution = await this.database.getExecution(executionId);
    const seen = new Set();
    while (execution && execution.replayOf && !seen.has(execution.executionId)) {
      seen.add(execution.executionId);
      const parent = await this.database.getExecution(execution.replayOf);
      if (!parent) break;
      execution = parent;
    }
    return execution;
  }

  // Full restart: re-seeds the flow's true origin's own initialMessage
  // (found via getRootExecution) as a brand-new execution, dispatched into
  // whatever the origin node is CURRENTLY wired to (see the /replay
  // endpoint) - always available, regardless of whether the flow has any
  // Mark Replay Point node at all. `restartedFrom` is whichever execution
  // the user actually clicked "Restart" on (for traceability), which may
  // itself be several replays deep - not necessarily the root.
  async beginRestart(executionId, flowId, flowName, seedMessage, originNodeId, restartedFrom, rootExecutionId) {
    await this.database.createExecution({
      executionId,
      flowId,
      flowName,
      originNodeId,
      initialMessage: safeClone(seedMessage),
      replayOf: restartedFrom,
      replayMode: 'restart',
      rootExecutionId
    });

    this.executionMap.set(executionId, {
      status: 'RUNNING',
      startTime: Date.now(),
      originNodeId,
      autoReplayAttempt: 0
    });

    await this.database.recordMessage(executionId, originNodeId, seedMessage, 'input', {
      nodeName: flowName,
      isFirst: true,
      isRestarted: true
    });

    await this.database.recordReplayLink(restartedFrom, executionId);
  }

  // Resumes from a specific previously-recorded message at a specific node -
  // either a developer-marked Mark Replay Point checkpoint (mode
  // 'checkpoint') or, only when explicitly enabled via settings, literally
  // any node the execution passed through (mode 'debug' - see the /replay
  // endpoint's execHistoryUnsafeReplay gate). Both dispatch into the SAME
  // node that recorded the message, letting it genuinely run again.
  //
  // originNodeId is set to that node (nodeId) - the /replay endpoint calls
  // node.receive() on it directly, so its own completion fires the normal
  // onComplete hook like any other node. recordNodeExit's origin-skip
  // (nodeId === execution.originNodeId) then prevents that from being
  // recorded as a second, redundant message - exactly as it already does
  // for a real inject/http-in origin's own completion.
  //
  // mode 'checkpoint' flags each seed isReplayPoint: true - since these
  // messages genuinely sit at a Mark Replay Point node, THIS execution, if
  // it later fails too, has its own valid checkpoint(s) to resume from
  // again. mode 'debug' deliberately does NOT set isReplayPoint - an
  // unsafe, arbitrary resume point shouldn't silently become a dev-blessed
  // checkpoint just because someone used it once; debug mode's own
  // "any node" candidate list already covers replaying it again anyway.
  // mode 'auto' is the same mechanism, triggered by the runtime itself (see
  // execution-resilience.js's recordFailure) rather than a human - flags
  // isAutoReplayPoint/isAutoReplayed instead, and additionally stamps
  // `attempt` onto the execution as autoReplayAttempt (0 for a
  // human-triggered checkpoint/debug resume, so a manual replay never
  // counts against - or is blocked by - the automatic retry budget).
  //
  // seedMessages is an ARRAY, not a single message - a node downstream of a
  // Split (and everything until its matching Join) runs once per part, so
  // it can have several recorded messages for the same execution. Resuming
  // from just ONE of those parts would leave a downstream Join waiting
  // forever for the rest; resuming from ALL of them - each dispatched here,
  // each still carrying its original msg.parts metadata unchanged - lets
  // Join recombine them exactly as it would have the first time. A
  // non-split node simply has one entry in this array, same mechanism.
  async beginResume(mode, executionId, flowId, flowName, seedMessages, nodeId, nodeName, messageIds, replayOf, attempt = 0, rootExecutionId, isAutoCheckpoint = false) {
    await this.database.createExecution({
      executionId,
      flowId,
      flowName,
      originNodeId: nodeId,
      initialMessage: safeClone(seedMessages[0]),
      replayOf,
      replayMode: mode,
      replayFromNodeId: nodeId,
      replayFromMessageIds: messageIds,
      autoReplayAttempt: attempt,
      rootExecutionId
    });

    this.executionMap.set(executionId, {
      status: 'RUNNING',
      startTime: Date.now(),
      originNodeId: nodeId,
      autoReplayAttempt: attempt
    });

    // nodeName is the resumed node's own name (e.g. "After DB Write"), not
    // flowName - unlike a real origin's one input entry, this seed message
    // didn't come from the flow firing again, and labeling it with the flow
    // name would misleadingly suggest it did.
    const options = { nodeName, isFirst: true };
    if (mode === 'checkpoint') {
      options.isReplayPoint = true;
      options.isReplayed = true;
    } else if (mode === 'auto') {
      options.isAutoReplayPoint = true;
      options.isAutoReplayed = true;
    } else {
      options.isDebugResume = true;
    }

    // Carries the auto-replay-point flag forward across a MANUAL resume too
    // (mode 'auto' already sets it above, unconditionally) - otherwise a
    // checkpoint/debug resume through an actual Mark Auto Replay Point node
    // would only ever be recognized as one the first time; a later manual
    // replay from what is still architecturally the same node would
    // silently lose its "auto" tag and the reset-count question in the
    // dashboard's Replay dialog, since THIS seed message would otherwise
    // only be flagged isReplayPoint/isDebugResume.
    if (isAutoCheckpoint && mode !== 'auto') {
      options.isAutoReplayPoint = true;
    }

    for (const seedMessage of seedMessages) {
      await this.database.recordMessage(executionId, nodeId, seedMessage, 'input', options);
    }

    await this.database.recordReplayLink(replayOf, executionId, { autoTriggered: mode === 'auto' });
  }

  // Fired on an auto-replay-point node's SECOND output once its retry
  // budget is exhausted and the final attempt has also failed - a
  // brand-new tracked execution (never a plain untracked message), so
  // anything wired downstream of the exhausted output stays fully
  // observable. Deliberately not flagged isReplayPoint/isAutoReplayPoint -
  // this is a terminal escape hatch, not itself a resumable checkpoint.
  async beginAutoExhausted(executionId, flowId, flowName, seedMessage, nodeId, nodeName, replayOf, rootExecutionId) {
    await this.database.createExecution({
      executionId,
      flowId,
      flowName,
      originNodeId: nodeId,
      initialMessage: safeClone(seedMessage),
      replayOf,
      replayMode: 'auto-exhausted',
      rootExecutionId
    });

    this.executionMap.set(executionId, {
      status: 'RUNNING',
      startTime: Date.now(),
      originNodeId: nodeId,
      autoReplayAttempt: 0
    });

    await this.database.recordMessage(executionId, nodeId, seedMessage, 'input', {
      nodeName,
      isFirst: true
    });

    await this.database.recordReplayLink(replayOf, executionId, { autoTriggered: true, exhausted: true });
  }

  // Thin wrappers around the additive scheduledRetry annotation - see
  // mongodb-adapter.js for why this lives as a field on the FAILED
  // execution rather than a new status value, and why claimScheduledRetry
  // is atomic (a live setTimeout and the startup reconciliation scan race
  // to fire the same retry; only one may win).
  async markAwaitingRetry(executionId, dueAt, attempt, nodeId, messageIds) {
    await this.database.markAwaitingRetry(executionId, dueAt, attempt, nodeId, messageIds);
  }

  async claimScheduledRetry(executionId) {
    return await this.database.claimScheduledRetry(executionId);
  }

  async clearScheduledRetry(executionId) {
    await this.database.clearScheduledRetry(executionId);
  }

  async markRetriesExhausted(executionId) {
    await this.database.markRetriesExhausted(executionId);
  }

  async getPendingAutoRetries() {
    return await this.database.getPendingAutoRetries();
  }

  async getExecutionWithMessages(executionId) {
    const execution = await this.database.getExecution(executionId);
    if (!execution) return null;

    const [messages, edges] = await Promise.all([
      this.database.getExecutionMessages(executionId),
      this.database.getExecutionEdges(executionId)
    ]);

    return {
      ...execution,
      messages,
      edges
    };
  }

  // edges: array of { sourcePort, destinationNodeId } - see recordEdges on
  // the database adapter for what these represent.
  async recordEdges(executionId, sourceNodeId, edges) {
    await this.database.recordEdges(executionId, sourceNodeId, edges);
  }

  async listExecutions(filter = {}, options = {}) {
    return await this.database.listExecutions(filter, options);
  }

  async listExecutionsGrouped(filter = {}, options = {}) {
    return await this.database.listExecutionsGrouped(filter, options);
  }

  async getExecutionChain(rootExecutionId) {
    return await this.database.getExecutionChain(rootExecutionId);
  }

  async deleteExecution(executionId) {
    this.executionMap.delete(executionId);
    await this.database.deleteExecution(executionId);
  }

  // cutoffDate === null deletes everything
  async clearExecutions(cutoffDate) {
    return await this.database.clearExecutions(cutoffDate);
  }

  async getStatistics() {
    return await this.database.getStatistics();
  }

  async getDistinctFlows() {
    return await this.database.getDistinctFlows();
  }

  async searchExecutions(searchTerm, filter = {}, options = {}) {
    return await this.database.searchMessages(searchTerm, filter, options);
  }
}

module.exports = ExecutionManager;
